### ISSUE TITLE
"knife spork upload COOKBOOK" show /var/chef/cache/checksums permission error

### ISSUE THREAD

**Issue by parnurzeal** [jonlives/knife-spork#118]
`knife spork check` is fine as following:

```
[jenkins@jenkins theeraphol-chef-repo]$ knife spork check git-cookbook
Checking versions for cookbook git-cookbook...

Local Version:
  0.1.0

Remote Versions: (* indicates frozen)
git-cookbook does not yet exist on the Chef Server!

git-cookbook does not yet exist on the Chef Server!
Everything looks good!
```

But `knife spork upload git-cookbook` gives me an error.

```
ERROR: Errno::EACCES: Permission denied - /var/chef/cache/checksums
```

I put my knife.rb --> chef-repo/.chef/knife.rb
Follow is my knife.rb

```
current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                'admin'
client_key               '/var/lib/jenkins/.chef/admin.pem'
validation_client_name   'chef-validator'
validation_key           '/var/lib/jenkins/.chef/chef-validator.pem'
chef_server_url          'https://chef-server.localdomain:443'
cookbook_path        ["#{current_dir}/../cookbooks"]
#cookbook_path      ["/var/lib/jenkins/theeraphol-chef-repo/cookbooks"]
```

**Comment by kiranemail3** [comment]
Hi Parnurzeal,

Can you pleas help me in this. I am also getting same error.
user1@ubuntu:~/chef-repo$ knife cookbook upload apache
Uploading apache       [0.1.0]
ERROR: Errno::EACCES: Permission denied - /var/chef/cache/checksums

below is my knife.rb output

user1@ubuntu:~/chef-repo/.chef$ cat knife.rb
# See http://docs.chef.io/config_rb_knife.html for more information on knife con              figuration options

current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "kiranemail3"
client_key               "#{current_dir}/kiranemail3.pem"
validation_client_name   "batch001-validator"
validation_key           "#{current_dir}/batch001-validator.pem"
chef_server_url          "https://api.chef.io/organizations/batch001"
cookbook_path            ["#{current_dir}/../cookbooks"]
