### ISSUE TITLE
Improvement: Git Plugin

### ISSUE THREAD

**Issue by TheSerapher** [jonlives/knife-spork#157]
Hey all,

I think it would be wonderful if the Git plugin could be expanded to also work for all other Chef related tasks. Opscode does depend on Git whenever you read their documentation and the Chef Repo is mentioned everywhere. Since Opscode does not have a variable solution to auto-commit and push to git, maybe spork can do this part.

Since spork already offers the API, maybe it is possible to add the Git module to all other parts related to knife administration (environment/role/data bag/node create/delete/edit). That way no Git commands can be forgotten and a workflow can be implemented easily by taking a human factor out of the equation.

**Comment by jonlives** [comment]
@TheSerapher I'd like to get this reviewed, tested and in the 1.5.0 release in the next couple of days if possible - would you be able to please submit the above as a pull request? That way the repo history clearly shows what changed etc and makes this easier to check over.

**Comment by TheSerapher** [comment]
@jonlives I am not sure if I can. This thing I wrote is a drop-in plugin to Spork using `.chef/plugins/knife/knife-git-all.rb` as the source file. I guess it would need to be added to the Git command already existing in Spork?

**Comment by jonlives** [comment]
@TheSerapher sure you can - if you create a fork of knife-spork and then add your GitAll plugin to that in the https://github.com/jonlives/knife-spork/tree/master/lib/knife-spork/plugins directory, then create a PR to this repo I'll take a look at it and see if it makes sense to replace the existing Git plugin wholesale or whatever :)

Could you please also (in case I keep it as a separate plugin) add the documentation for your new plugin to https://github.com/jonlives/knife-spork/tree/master/plugins as an .md file :)

Hope that clears things up a little - lemme know if I didn't make sense :)

**Comment by TheSerapher** [comment]
Makes sense! I will see what I can do :-) Rather busy at the moment but maybe I can find some spare time.

**Comment by jonlives** [comment]
@TheSerapher awesome thanks - if you don't think you'll be able to get to this in the next couple of days, let me know and I'll bump it to the next release milestone :)

**Comment by jeunito** [comment]
@TheSerapher also have some features for the git plugin in https://github.com/jonlives/knife-spork/pull/155. I am willing to take a stab at merging both our stuff to help out. I have done some work in this plugin and I am familiar with the flow of the code.

**Comment by TheSerapher** [comment]
Yes, please go ahead. I can commit the GitAll module but to be honest a simple copy from my sample into the Git core plugin will probably do the trick.=

**Comment by jeunito** [comment]
@jonlives I made a pull for the git_all plugin on https://github.com/jonlives/knife-spork/pull/173. @TheSerapher

**Comment by jonlives** [comment]
Moving to "Next Release" milestone per #173

**Comment by jonlives** [comment]
Closing this one in favour of #187
