### ISSUE TITLE
environment create should check target does not already exist.

### ISSUE THREAD

**Issue by mrjcleaver** [jonlives/knife-spork#171]
Witness:
````
 knife spork environment create development
````

**environment destroyed**

Oh no! I meant check! (yes, this happened)

**Comment by jonlives** [comment]
Should be easy enough to add a guard to check if the environment already exists and prompt for overwrite - at the moment spork is just wrapping knife environment create, which has no such guard.

**Comment by mrjcleaver** [comment]
Thx
