### ISSUE TITLE
Berkshelf integration (yes, again)

### ISSUE THREAD

**Issue by RSO** [jonlives/knife-spork#85]
At Factlink we're in the process of moving our setup from a single chef-repo with librarian-chef towards a repo-per-cookbook with Berkshelf setup. During this move we're taking on bugs as they show up, as I did with knife-spork's Berkshelf integration, only to later find out that knife-spork might not be so suiting for Berkshelf integration at all.

First I will describe our current setup/folder structure:

```
~/dev/
    chef-repo/
    chef-factlink-web/
    chef-factlink-database/
    chef-factlink-otherstuff/
```

Originally we packed a Berksfile in our chef-repo in which we'd state all the direct dependencies:

```
cookbook 'chef-factlink-web'
cookbook 'chef-factlink-database'
cookbook 'chef-factlink-otherstuff'
```

This caused a lot of overhead in the update/upload process with Berkshelf, which made me do some investigating on a fluid Berkshelf flow. In RiotGames/berkshelf#535 @reset states that the chef-repo should NOT contain a Berksfile and that all application cookbooks should manage their own dependencies, which kinda makes sense to me, although it introduces a new problem with setting up knife-spork integration with Berkshelf.

In #74 @sethvargo introduced a way to resolve cookbooks through Berkshelf, but this doesn't work completely with the flow that is proposed in RiotGames/berkshelf#535 since I'm no longer able to promote `chef-factlink-web` directly, since there is no place to resolve this.

As stated we just started using Berkshelf, so maybe I'm missing something in this flow, so I am interested in learning what the correct knife-spork/berkshelf flow looks like.

If we're doing everything correctly, but something is indeed still missing in the knife-spork/berkshelf integration, I would like to propose support for running knife-spork from out of a cookbook folder itself, something along the likes of:

```
knife spork promote ENVIRONMENT .
```

What do you think?

**Comment by loupgaroublond** [comment]
Hi there,

--cookbook-path does not unfuck up the Berkshelf integration, it just adds a new feature. Here's why:

Redacted.local:redacted-dir yankee$ knife spork promote development,staging,production  nagios -v 5.2.0 --cookbook-path ~/.berkshelf/cookbooks/
WARNING: Unloading Berkshelf as skip_berkshelf option found in config
ERROR: Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/yankee/.berkshelf/environments/development.json

It treats the berkshelf directory as the Chef project directory, which is double plus ungood for using this orthogonally from other settings. Yes, I know i can manually set these things in the spork-config.yml file,w which I will do now, but i shouldn't have to.
